version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app               # mount project code into container
      - /app/node_modules    # don't overwrite node_modules in container
    environment:
      - NODE_ENV=development
      - DATABASE_LOCAL=mongodb://mongo:27017/natours
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
